# Production - 5 реплик
replicaCount: 5
ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefic.ingress.kubernetes.io/router.middlewares: cv-site-redirect-to-https@kubernetescrd
  hosts:
    - host: devopsrk.duckdns.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cv-site-tls
      hosts:
        - devopsrk.duckdns.org
